// deno-lint-ignore-file no-explicit-any
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// This function handles both flows:
// 1. GET - YouCan redirects the browser here with ?code=...&state=...
// 2. POST - Frontend OAuthCallback calls this with { code, state } in JSON body
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    let code: string | null = null;
    let state: string | null = null;

    if (req.method === "GET") {
      const url = new URL(req.url);
      code = url.searchParams.get("code");
      state = url.searchParams.get("state");
    } else if (req.method === "POST") {
      const body = await req.json().catch(() => ({}));
      code = body.code ?? null;
      state = body.state ?? null;
    } else {
      return new Response(JSON.stringify({ error: "Method not allowed" }), {
        status: 405,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!code || !state) {
      throw new Error(`Missing code or state. code=${code}, state=${state}`);
    }

    // State format: "${timestamp}:${workspaceId}:${hmacSignature}"
    // Generated by youcan-generate-state edge function
    const stateParts = state.split(":");
    if (stateParts.length < 2) {
      throw new Error(`Invalid state format: ${state}`);
    }
    const workspaceId = stateParts[1]; // index 0 = timestamp, index 1 = workspaceId, index 2 = signature
    console.log(`[YouCan OAuth] Parsed workspaceId: ${workspaceId} from state: ${state.substring(0, 40)}...`);

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Verify workspace exists
    const { data: workspace, error: workspaceError } = await supabase
      .from("workspaces")
      .select("id")
      .eq("id", workspaceId)
      .single();

    if (workspaceError || !workspace) {
      throw new Error(`Workspace not found: ${workspaceId}`);
    }

    const YOUCAN_CLIENT_ID = Deno.env.get("YOUCAN_CLIENT_ID");
    const YOUCAN_CLIENT_SECRET = Deno.env.get("YOUCAN_CLIENT_SECRET");
    const YOUCAN_REDIRECT_URI = Deno.env.get("YOUCAN_REDIRECT_URI");

    console.log(
      `[YouCan OAuth] method=${req.method} ` +
      `client_id set: ${!!YOUCAN_CLIENT_ID} (len=${YOUCAN_CLIENT_ID?.length}), ` +
      `secret set: ${!!YOUCAN_CLIENT_SECRET} (len=${YOUCAN_CLIENT_SECRET?.length}), ` +
      `redirect_uri: ${YOUCAN_REDIRECT_URI}`
    );

    if (!YOUCAN_CLIENT_ID || !YOUCAN_CLIENT_SECRET) {
      throw new Error("YOUCAN_CLIENT_ID / YOUCAN_CLIENT_SECRET not configured in Supabase secrets");
    }
    if (!YOUCAN_REDIRECT_URI) {
      throw new Error("YOUCAN_REDIRECT_URI not configured in Supabase secrets");
    }

    // Exchange code for token
    const tokenRes = await fetch("https://api.youcan.shop/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        client_id: YOUCAN_CLIENT_ID,
        client_secret: YOUCAN_CLIENT_SECRET,
        redirect_uri: YOUCAN_REDIRECT_URI,
        code,
      }),
    });

    const responseText = await tokenRes.text();
    console.log(
      `[YouCan OAuth] Token exchange status: ${tokenRes.status}, body: ${responseText.substring(0, 500)}`
    );

    if (!tokenRes.ok) {
      throw new Error(`YouCan API error (${tokenRes.status}): ${responseText}`);
    }

    let token: any;
    try {
      token = JSON.parse(responseText);
    } catch {
      throw new Error(`Invalid JSON from YouCan (${tokenRes.status}): ${responseText.substring(0, 500)}`);
    }

    // Calculate expiration time
    const expiresAt = new Date(Date.now() + token.expires_in * 1000).toISOString();

    // Store tokens
    const { error: updateError } = await supabase
      .from("workspaces")
      .update({
        youcan_access_token: token.access_token,
        youcan_refresh_token: token.refresh_token,
        youcan_token_expires_at: expiresAt,
      })
      .eq("id", workspaceId);

    if (updateError) {
      throw new Error(`Failed to store tokens: ${updateError.message}`);
    }

    // For GET (browser redirect from YouCan), redirect to the app settings page
    if (req.method === "GET") {
      const FRONTEND_URL = Deno.env.get("FRONTEND_URL") || "https://ecomscale.vercel.app";
      return Response.redirect(`${FRONTEND_URL}/settings?tab=integrations&youcan=success`, 302);
    }

    // For POST (called from frontend OAuthCallback), return JSON
    return new Response(JSON.stringify({ success: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (err: any) {
    console.error("[YouCan OAuth] Error:", err.message);

    // For GET requests (browser), redirect to settings with error info
    if (req.method === "GET") {
      const FRONTEND_URL = Deno.env.get("FRONTEND_URL") || "https://ecomscale.vercel.app";
      const encodedError = encodeURIComponent(err.message.substring(0, 200));
      return Response.redirect(
        `${FRONTEND_URL}/settings?tab=integrations&youcan=error&details=${encodedError}`,
        302
      );
    }

    return new Response(JSON.stringify({ error: err.message }), {
      status: 400,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
