import { useCallback, useEffect, useState, type ReactNode } from "react";
import { Loader2, MessageSquareText } from "lucide-react";
import { founderAdmin, type SupportTicket } from "../../../lib/founderAdmin";
import { EmptyState, PageHeading, RefreshButton, StatusBadge, errorMessage } from "./shared";

export function SupportPageV3() {
  const [tickets, setTickets] = useState<SupportTicket[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<SupportTicket | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setTickets(await founderAdmin.tickets()); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <div className="mx-auto max-w-7xl p-4 md:p-6 lg:p-8"><PageHeading eyebrow="Support" title="Tickets & Support Mode" description="Manage real user tickets through protected RPCs. Workspace Support Mode sessions are directly opened from User 360° and remain audit logged." action={<RefreshButton onClick={() => void load()} loading={loading} />}/>{error ? <EmptyState title="Could not load tickets" copy={error} /> : <div className="grid gap-4 lg:grid-cols-2">{loading ? <div className="col-span-full grid h-52 place-items-center"><Loader2 className="animate-spin text-brand-accent" /></div> : tickets.length ? tickets.map((ticket) => <article key={ticket.id} className="rounded-xl border border-base-border bg-base-surface p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{ticket.subject}</h3><p className="mt-1 text-xs text-ink-muted">{ticket.requester_email || "Unknown requester"} · {ticket.workspace_name || "No workspace"}</p></div><div className="flex gap-1.5"><StatusBadge value={ticket.priority} /><StatusBadge value={ticket.status} /></div></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-ink-muted">{ticket.message}</p><div className="mt-5 flex justify-end"><button onClick={() => setSelected(ticket)} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-accent px-3 py-2 text-xs font-bold text-white"><MessageSquareText size={14} />Manage</button></div></article>) : <div className="col-span-full"><EmptyState title="No support tickets" copy="Tickets submitted by users will appear here." /></div>}</div>}{selected && <TicketDialog ticket={selected} onClose={() => setSelected(null)} onSaved={async (status, priority, reply, internal) => { await founderAdmin.updateTicket(selected.id, status, priority, reply, internal); setSelected(null); await load(); }} />}</div>;
}

function TicketDialog({ ticket, onClose, onSaved }: { ticket: SupportTicket; onClose: () => void; onSaved: (status: SupportTicket["status"], priority: SupportTicket["priority"], reply: string, internal: boolean) => Promise<void> }) { const [status, setStatus] = useState<SupportTicket["status"]>(ticket.status); const [priority, setPriority] = useState<SupportTicket["priority"]>(ticket.priority); const [reply, setReply] = useState(""); const [internal, setInternal] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><form onSubmit={async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await onSaved(status, priority, reply, internal); } catch (err) { setError(errorMessage(err)); } finally { setSaving(false); } }} className="w-full max-w-lg rounded-2xl border border-base-border bg-base-surface p-5 shadow-2xl"><h3 className="text-lg font-bold">Manage ticket</h3><p className="mt-1 text-sm text-ink-muted">{ticket.subject}</p>{error && <p className="mt-3 rounded-lg bg-danger/10 px-3 py-2 text-sm text-danger">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Status"><select value={status} onChange={(e) => setStatus(e.target.value as SupportTicket["status"])} className="field"><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_on_customer">Waiting on customer</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></Field><Field label="Priority"><select value={priority} onChange={(e) => setPriority(e.target.value as SupportTicket["priority"])} className="field"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field></div><Field label="Reply"><textarea value={reply} onChange={(e) => setReply(e.target.value)} rows={4} className="field resize-y" /></Field><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={internal} onChange={(e) => setInternal(e.target.checked)} />Internal note</label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-base-border px-3 py-2 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-lg bg-brand-accent px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save ticket"}</button></div></form></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="mt-4 block text-xs font-bold uppercase tracking-wide text-ink-faint">{label}<span className="mt-2 block">{children}</span></label>; }
