-- Migration: Add city aliases table for common Moroccan city nicknames
-- This allows users to search for cities using common abbreviations/surnames

CREATE TABLE IF NOT EXISTS public.city_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ozon_city_id bigint NOT NULL,
  alias text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Add indexes for fast alias lookups
CREATE INDEX IF NOT EXISTS city_aliases_alias_idx ON public.city_aliases (alias);
CREATE INDEX IF NOT EXISTS city_aliases_ozon_city_id_idx ON public.city_aliases (ozon_city_id);
CREATE INDEX IF NOT EXISTS city_aliases_alias_trgm_idx ON public.city_aliases USING gin (alias gin_trgm_ops);

-- Add foreign key constraint
ALTER TABLE public.city_aliases
  ADD CONSTRAINT fk_city_aliases_ozon_city
  FOREIGN KEY (ozon_city_id)
  REFERENCES public.ozon_cities(id)
  ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.city_aliases ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read city_aliases (it's a reference table)
CREATE POLICY "city_aliases_read_all" ON public.city_aliases
  FOR SELECT USING (true);

-- Policy: Allow inserts for data import (managed via scripts)
CREATE POLICY "city_aliases_insert_all" ON public.city_aliases
  FOR INSERT WITH CHECK (true);

CREATE POLICY "city_aliases_no_update" ON public.city_aliases
  FOR UPDATE USING (false);

CREATE POLICY "city_aliases_no_delete" ON public.city_aliases
  FOR DELETE USING (false);

-- Add comment
COMMENT ON TABLE public.city_aliases IS 'Common nicknames/abbreviations for Moroccan cities to improve search UX';
COMMENT ON COLUMN public.city_aliases.ozon_city_id IS 'Reference to ozon_cities.id';
COMMENT ON COLUMN public.city_aliases.alias IS 'Common nickname or abbreviation for the city';
