-- Migration: Add Arabic city names mapping
-- This allows proper resolution of Arabic city names

CREATE TABLE IF NOT EXISTS public.city_arabic_names (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ozon_city_id bigint NOT NULL,
  arabic_name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Add indexes for fast Arabic name lookups
CREATE INDEX IF NOT EXISTS city_arabic_names_arabic_name_idx ON public.city_arabic_names (arabic_name);
CREATE INDEX IF NOT EXISTS city_arabic_names_ozon_city_id_idx ON public.city_arabic_names (ozon_city_id);

-- Add foreign key constraint
ALTER TABLE public.city_arabic_names
  ADD CONSTRAINT fk_city_arabic_names_ozon_city
  FOREIGN KEY (ozon_city_id)
  REFERENCES public.ozon_cities(id)
  ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.city_arabic_names ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read city_arabic_names (it's a reference table)
CREATE POLICY "city_arabic_names_read_all" ON public.city_arabic_names
  FOR SELECT USING (true);

-- Policy: Allow inserts for data import (managed via scripts)
CREATE POLICY "city_arabic_names_insert_all" ON public.city_arabic_names
  FOR INSERT WITH CHECK (true);

CREATE POLICY "city_arabic_names_no_update" ON public.city_arabic_names
  FOR UPDATE USING (false);

CREATE POLICY "city_arabic_names_no_delete" ON public.city_arabic_names
  FOR DELETE USING (false);

-- Add comment
COMMENT ON TABLE public.city_arabic_names IS 'Arabic names for Moroccan cities to support Arabic city resolution';
COMMENT ON COLUMN public.city_arabic_names.ozon_city_id IS 'Reference to ozon_cities.id';
COMMENT ON COLUMN public.city_arabic_names.arabic_name IS 'Arabic name of the city';
